

class Timers(object):

    #Timers that are already taken: 1, 2, 3, 4, 7
   
    RUN = 7
    CHANGE_EMG = 15

    MOTOR1_PWM = 1
    MOTOR1_PWM_CHANNEL = 2

    MOTOR1_ENC = 4
    MOTOR1_ENC_A_CHANNEL = 1
    MOTOR1_ENC_B_CHANNEL = 2


    MOTOR2_PWM = 1
    MOTOR2_PWM_CHANNEL = 1

    MOTOR2_ENC = 3
    MOTOR2_ENC_A_CHANNEL = 1
    MOTOR2_ENC_B_CHANNEL = 2

    MOTOR3_PWM = 1
    MOTOR3_PWM_CHANNEL = 3

    MOTOR3_ENC = 2
    MOTOR3_ENC_A_CHANNEL = 1
    MOTOR3_ENC_B_CHANNEL = 2

    SERVO_PWM = 14
    SERVO_PWM_CHANNEL = 1